/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
*/

function getSolution(){
  var maxFibonacciValue = 4000000;
  var prev = 1;
  var current = 2;
  var sum = current;
  var temp;
  //iterative over recursive fibonacci.
  while(sum < maxFibonacciValue){
    temp = current;
    current += prev;
    prev = temp;
    if(current % 2 === 0)
      sum += current
  }
  return sum;
}

module.exports = {
  getSolution
}
